version: "3.9"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
  mongo-products:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-products-data:/data/db
    networks:
      - backend

  auth-service:
    build: ./auth-service
    restart: unless-stopped
    env_file:
      - auth-service/.env
    depends_on:
      - mongo
    networks:
      - backend
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  products-service:
    build: ./microservices-products
    restart: unless-stopped
    env_file:
      - microservices-products/.env
    depends_on:
      - mongo-products
    networks:
      - backend
    volumes:
      - ./microservices-products:/app
      - /app/node_modules

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    env_file:
      - api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - products-service
    networks:
      - backend
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

volumes:
  mongo-data:
  mongo-products-data:

networks:
  backend:
